# Generated by Django 3.1.6 on 2021-02-12 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210205_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='nameTask',
        ),
    ]
